# Generated by Django 6.0.3 on 2026-03-29 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('roupa', 'Roupa'), ('calcado', 'Calçado'), ('acessorio', 'Acessório'), ('perfumaria', 'Perfumaria')], max_length=20)),
                ('subcategoria', models.CharField(choices=[('camisa', 'Camisa'), ('calca', 'Calça'), ('bermuda', 'Bermuda'), ('tenis', 'Tênis'), ('cinto', 'Cinto'), ('bijuteria', 'Bijuteria Masculina'), ('perfume', 'Perfume')], max_length=20)),
                ('marca', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='app.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('tamanho', models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('U', 'Único')], max_length=2, null=True)),
                ('numeracao', models.CharField(blank=True, choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46')], max_length=2, null=True)),
                ('saldo_atual', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='app.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='app.variacao')),
            ],
        ),
    ]
