# Generated by Django 6.0.3 on 2026-04-08 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ('nome',), 'verbose_name': 'fornecedor', 'verbose_name_plural': 'fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ('-data', '-id'), 'verbose_name': 'movimentacao', 'verbose_name_plural': 'movimentacoes'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'ordering': ('user__username',), 'verbose_name': 'perfil de usuario', 'verbose_name_plural': 'perfis de usuario'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('nome',), 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.AlterModelOptions(
            name='variacao',
            options={'ordering': ('produto__nome', 'cor', 'tamanho', 'numeracao'), 'verbose_name': 'variacao', 'verbose_name_plural': 'variacoes'},
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('funcionario', 'Funcionario')], default='funcionario', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('roupa', 'Roupa'), ('calcado', 'Calcado'), ('acessorio', 'Acessorio'), ('perfumaria', 'Perfumaria')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(choices=[('camisa', 'Camisa'), ('calca', 'Calca'), ('bermuda', 'Bermuda'), ('tenis', 'Tenis'), ('cinto', 'Cinto'), ('bijuteria', 'Bijuteria Masculina'), ('perfume', 'Perfume')], max_length=20),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='tamanho',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('U', 'Unico')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='ImportacaoNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, null=True, unique=True)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('fornecedor_nome', models.CharField(blank=True, max_length=150)),
                ('fornecedor_documento', models.CharField(blank=True, max_length=18)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('arquivo_nome', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_nota_fiscal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'importacao de nota fiscal',
                'verbose_name_plural': 'importacoes de nota fiscal',
                'ordering': ('-criado_em', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ImportacaoNotaFiscalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField()),
                ('codigo_produto', models.CharField(blank=True, max_length=60)),
                ('descricao_produto', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.importacaonotafiscal')),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_importacao_nota_fiscal', to='app.movimentacao')),
                ('variacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_importacao_nota_fiscal', to='app.variacao')),
            ],
            options={
                'verbose_name': 'item de importacao de nota fiscal',
                'verbose_name_plural': 'itens de importacao de nota fiscal',
                'ordering': ('indice', 'id'),
                'unique_together': {('importacao', 'indice')},
            },
        ),
    ]
