# Generated by Django 6.0.3 on 2026-04-08 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_fornecedor_options_alter_movimentacao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='EstoquePro', max_length=120)),
                ('descricao_empresa', models.CharField(default='Gestao inteligente de estoque', max_length=160)),
                ('logo', models.FileField(blank=True, null=True, upload_to='branding/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'svg'])])),
                ('cor_primaria', models.CharField(default='#1768AC', max_length=7)),
                ('cor_secundaria', models.CharField(default='#0F4C81', max_length=7)),
                ('cor_acento', models.CharField(default='#F97316', max_length=7)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuracao do sistema',
                'verbose_name_plural': 'configuracoes do sistema',
            },
        ),
    ]
