# Generated by Django 6.0.3 on 2026-04-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_configuracaosistema_atualizado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='documento',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
