# Generated by Django 6.0.3 on 2026-04-08 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_fornecedor_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=120)),
                ('cliente_documento', models.CharField(blank=True, max_length=18, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_venda_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido de venda',
                'verbose_name_plural': 'pedidos de venda',
                'ordering': ('-criado_em', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PedidoVendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movimentacao_estorno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido_venda_estorno', to='app.movimentacao')),
                ('movimentacao_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido_venda_saida', to='app.movimentacao')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.pedidovenda')),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido_venda', to='app.variacao')),
            ],
            options={
                'verbose_name': 'item do pedido de venda',
                'verbose_name_plural': 'itens do pedido de venda',
                'ordering': ('id',),
                'unique_together': {('pedido', 'variacao')},
            },
        ),
    ]
