# Generated by Django 6.0.3 on 2026-04-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_movimentacao_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cest',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cfop',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_comercial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('roupa', 'Roupa'), ('calcado', 'Calcado'), ('acessorio', 'Acessorio'), ('perfumaria', 'Perfumaria'), ('geral', 'Geral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(choices=[('camisa', 'Camisa'), ('calca', 'Calca'), ('bermuda', 'Bermuda'), ('tenis', 'Tenis'), ('cinto', 'Cinto'), ('bijuteria', 'Bijuteria Masculina'), ('perfume', 'Perfume'), ('geral', 'Geral')], max_length=20),
        ),
    ]
