# Generated by Django 6.0.3 on 2026-04-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_produto_cest_produto_cfop_produto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importacaonotafiscalitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='importacaonotafiscal',
            name='importado_por',
        ),
        migrations.RemoveField(
            model_name='importacaonotafiscalitem',
            name='importacao',
        ),
        migrations.RemoveField(
            model_name='importacaonotafiscalitem',
            name='movimentacao',
        ),
        migrations.RemoveField(
            model_name='importacaonotafiscalitem',
            name='variacao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cest',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cfop',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ncm',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='unidade_comercial',
        ),
        migrations.DeleteModel(
            name='ConfiguracaoSistema',
        ),
        migrations.DeleteModel(
            name='ImportacaoNotaFiscal',
        ),
        migrations.DeleteModel(
            name='ImportacaoNotaFiscalItem',
        ),
    ]
