# Generated by Django 6.0.3 on 2026-04-30 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_importacaonotafiscal_importado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidovenda',
            options={'ordering': ('-criado_em', '-id'), 'verbose_name': 'venda', 'verbose_name_plural': 'vendas'},
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='pedidovenda',
            name='cliente_documento',
        ),
        migrations.RemoveField(
            model_name='pedidovenda',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='pedidovendaitem',
            name='movimentacao_estorno',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='data_referencia',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='app.fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='contato',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='status',
            field=models.CharField(choices=[('finalizado', 'Finalizado')], default='finalizado', max_length=20),
        ),
    ]
