# Generated by Django 6.0.3 on 2026-05-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_pedidovenda_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ('-data', '-id'), 'verbose_name': 'movimentação', 'verbose_name_plural': 'movimentações'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'ordering': ('user__username',), 'verbose_name': 'perfil de usuário', 'verbose_name_plural': 'perfis de usuário'},
        ),
        migrations.AlterModelOptions(
            name='variacao',
            options={'ordering': ('produto__nome', 'cor', 'tamanho', 'numeracao'), 'verbose_name': 'variação', 'verbose_name_plural': 'variações'},
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('funcionario', 'Funcionário')], default='funcionario', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('roupa', 'Roupa'), ('calcado', 'Calçado'), ('acessorio', 'Acessório'), ('perfumaria', 'Perfumaria'), ('geral', 'Geral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(choices=[('camisa', 'Camisa'), ('calca', 'Calça'), ('bermuda', 'Bermuda'), ('tenis', 'Tênis'), ('cinto', 'Cinto'), ('bijuteria', 'Bijuteria Masculina'), ('perfume', 'Perfume'), ('geral', 'Geral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='tamanho',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('U', 'Único')], max_length=2, null=True),
        ),
    ]
